### ISSUE TITLE
test folder excluded in some builds

### ISSUE THREAD

**Issue by thameera** [danday74/git-diff#1]
For example, electron-builder excludes all the test folders of node_modules by default. Since the implementation relies on the test folder in this module, it fails after bundling.

It would be good to either rename the test folder to something else or not rely on anything in the test folder for core functionality. 

(For now I've created a fork of the project, renamed the folder and used it.)

Really useful project by the way! Thanks for taking the time to build it and release open source.

**Comment by danday74** [comment]
thanks thats really useful info - I didn't know about that - will avoid in future

Have fixed it by moving the file the implementation uses outside of the test folder.

Fixed in 2.0.6 release

Thanks again

**Comment by thameera** [comment]
Thank you very much!
