### ISSUE TITLE
Headers not existent 

### ISSUE THREAD

**Issue by floydding** [danday74/git-diff#4]
Hi I am trying to use this awesome tool but the diff string generated doesn't have the header like this
```
@@ -2557,6 +2557,11 @@
```

i only got pure diff string
```
{
 	"key1": "value1",
 	"key2": "value1",
 	"key3": "value1",
 	"key4": "value1",
 	"key5": "value1",
-	"key6": "value6",
 	"key7": "value1",
 	"key8": "value1",
 	"key9": "value1",
 	"key10": "value1",
 	"key11": "value1",
-	"key12": "value6"
+	"key12": "value600000"
 }

```
I am not sure what part goes wrong, is it something wrong with my local git? thanks

**Comment by floydding** [comment]
btw I do have git available. I saw FAQ section saying if no header then something is not ready. I don't quite know where I am missing. Thanks

**Comment by danday74** [comment]
To work fully, this needs git installed and access to the printf command. Does printf work in your console / available on your system? If not then it is falling back to a fake git diff, which won't have the header.
